
project_id = "ybqfivanagbklfyqsatw"

[functions.create-checkout]
verify_jwt = true

[functions.customer-portal] 
verify_jwt = true

[functions.check-subscription]
verify_jwt = true

[functions.setup-stripe-products]
verify_jwt = true

[functions.setup-storage]
verify_jwt = true
