
# This file is used to configure the Supabase CLI
# When you run "supabase init", it will be created for you

[project]
project_id = "ohxecbcihwinyskhaysl"

[api]
port = 54321
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320

[studio]
port = 54323

[inbucket]
port = 54324

[storage]
file_size_limit = "50MiB"

[functions.delete-building]
verify_jwt = true

