// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tbufqwllakmiyhhowfqs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRidWZxd2xsYWttaXloaG93ZnFzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYyMTcxODMsImV4cCI6MjA2MTc5MzE4M30.QhQV9GaNsXrDbnUmhj7JD3ki4OkOB8DGhae41h6LMxw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
    storage: typeof window !== 'undefined' ? localStorage : null
  }
});
