// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ybqfivanagbklfyqsatw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlicWZpdmFuYWdia2xmeXFzYXR3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcxNTcyNDAsImV4cCI6MjA2MjczMzI0MH0.i099YXDs931beytt1X3xibw6H9Fqe_emQ-lGdGz9jdQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);